version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password

    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rails db:create db:schema:load RAILS_ENV=test
      - run: bundle exec rspec spec
      - run: bundle exec rubocop -c .rubocop.yml
      - run: bundle exec brakeman
